# Generated by Django 4.2.4 on 2023-09-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_get_html_article_is_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='get_html',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_html',
        ),
    ]
