# Generated by Django 4.2.4 on 2023-09-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_get_html_remove_article_is_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='html_content',
            field=models.TextField(default='', verbose_name='html_content'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
    ]
