# Generated by Django 4.2.4 on 2023-09-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_html_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='html_content',
            field=models.TextField(blank=True, null=True, verbose_name='html_content'),
        ),
    ]
