# Generated by Django 4.2.4 on 2023-09-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_body_alter_article_html_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='html_toc',
            field=models.TextField(blank=True, null=True, verbose_name='html_toc'),
        ),
    ]
